### ISSUE TITLE
Missing rv32.ini

### ISSUE THREAD

**Issue by mongsim** [wyvernSemi/riscV#1]
Where I can find rv32.ini, and what is its function? Thank you.

**Comment by wyvernSemi** [comment]
The `rv32.ini` file is read by rv32 the instruction set simulator (ISS), if present in the run directory, and is used to configure the model in place of using the command line options (which can still be used to override the settings in the `rv32.ini` file).

Normally a user might cut-and-paste the example `rv32.ini` file in the documentation into a `rv32.ini` file in their run directory and modify it to suit their needs (see section _Initialisation File_ on page 31 of the [ISS documentation, v0.26](https://github.com/wyvernSemi/riscV/blob/main/iss/doc/iss_manual.pdf)) . However, I have now provided examples and added `rv32.ini` files to the `iss/` and `freertos/` directories. The former is configured for the default values, whilst the latter is suitable for running the FreeRTOS demo code without the need for command line arguments.
